-- The account store, in Postgres.
--
-- Run this once per Supabase project — local and production each need it. Paste it into the
-- Supabase SQL editor (Dashboard → SQL Editor → New query → Run), or pipe it through psql. It is
-- written to be safe to run twice: every statement is IF NOT EXISTS or CREATE OR REPLACE, so
-- re-running it after an edit will not drop anything or lose a row.
--
-- The column names are snake_case; `app/lib/store.ts` maps them to the camelCase fields the
-- application uses. Do not rename them without changing the COLUMN map in that file.

create table if not exists public.users (
  -- Generated by the application (`user_<base36 time>_<random>`), not by Postgres. The id is
  -- baked into every session token already issued, so it has to be the application's to mint.
  id text primary key,

  name text not null,

  -- Lower-cased and trimmed before it ever reaches here, by `createUser`. The unique index is what
  -- actually decides whether an address is taken: a read-then-insert would let two simultaneous
  -- sign-ups for the same address both pass the check, and PostgREST reports the violation as
  -- 23505, which the store turns back into "this email is already registered".
  email text not null unique,

  -- scrypt, as `<salt>:<derived key>`, both hex. Never leaves the server: `listUsers` strips it.
  password_hash text not null,

  plan text not null default 'Starter' check (plan in ('Starter', 'Pro', 'Elite')),

  -- Timestamps are text, holding the exact ISO-8601 string `new Date().toISOString()` produced,
  -- rather than timestamptz. That is deliberate. The application compares and sorts these as
  -- strings, and `subscribed_until` is a plain IST calendar date ("2026-08-11") compared against
  -- `todayIST()` with >=. Handing them to Postgres as timestamps means PostgREST returns them in
  -- its own format ("2026-08-11T00:00:00+00:00"), and those comparisons quietly stop agreeing with
  -- the ones the JSON backend makes. Text keeps the two backends byte-identical, which is the
  -- property that lets you develop against one and deploy against the other.
  -- ISO-8601 UTC sorts lexically in chronological order, so ORDER BY still does the right thing.
  created_at text not null,

  -- Ten digits, no country code or separators. Null on accounts created before the field existed.
  mobile text,

  role text not null default 'user' check (role in ('admin', 'user')),

  trial_started_at text,
  subscribed_until text,
  last_payment_id text,

  email_verified_at text,
  verification_token text,
  verification_sent_at text
);

-- Sign-in looks an account up by address on every attempt. The unique constraint above already
-- creates an index, so there is nothing further to add for that path.

-- Verification links are looked up by token, and the UPDATE that spends one is filtered on it.
-- Partial, because every verified account has a null here and there is no reason to index those.
create index if not exists users_verification_token_idx
  on public.users (verification_token)
  where verification_token is not null;

-- The admin dashboard lists newest first.
create index if not exists users_created_at_idx on public.users (created_at desc);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
--
-- This is the part that matters most, so read it before changing it.
--
-- A Supabase project's anon key is public by design — it is shipped in the browser bundle of any
-- app that uses one, and anyone can read it. PostgREST exposes every table to that key unless RLS
-- says otherwise. This table holds password hashes and live verification tokens.
--
-- So: RLS is enabled and NO policy is created. That combination denies everything to `anon` and
-- `authenticated`. The service_role key bypasses RLS entirely, and it is the only key the server
-- uses (SUPABASE_SERVICE_ROLE_KEY, never exposed to the browser, never NEXT_PUBLIC_).
--
-- Do not "fix" the fact that this table is unreadable from the client by adding a permissive
-- policy. Nothing in this application reads it from the client; every account read goes through a
-- route handler.

alter table public.users enable row level security;

-- Belt and braces: revoke the grants PostgREST's roles get by default, so the table is closed even
-- if RLS is later switched off by accident.
revoke all on public.users from anon, authenticated;
