-- The account store, in Postgres.
--
-- Run this once per Supabase project — local and production each need it. Paste it into the
-- Supabase SQL editor (Dashboard → SQL Editor → New query → Run), or pipe it through psql. It is
-- written to be safe to run twice: every statement is IF NOT EXISTS or CREATE OR REPLACE, so
-- re-running it after an edit will not drop anything or lose a row.
--
-- The column names are snake_case; `app/lib/store.ts` maps them to the camelCase fields the
-- application uses. Do not rename them without changing the COLUMN map in that file.

create table if not exists public.users (
  -- Generated by the application (`user_<base36 time>_<random>`), not by Postgres. The id is
  -- baked into every session token already issued, so it has to be the application's to mint.
  id text primary key,

  name text not null,

  -- Lower-cased and trimmed before it ever reaches here, by `createUser`. The unique index is what
  -- actually decides whether an address is taken: a read-then-insert would let two simultaneous
  -- sign-ups for the same address both pass the check, and PostgREST reports the violation as
  -- 23505, which the store turns back into "this email is already registered".
  email text not null unique,

  -- scrypt, as `<salt>:<derived key>`, both hex. Never leaves the server: `listUsers` strips it.
  password_hash text not null,

  -- Null until something is bought. An account starts on the three-day trial holding no plan at
  -- all, and it is the absence here — not a placeholder tier — that separates it from a paying
  -- Starter subscriber. Access is decided by `subscribed_until` and the trial clock; this column
  -- records *what* was bought, not whether it is still live.
  --
  -- Was `not null default 'Starter'`, which made every sign-up indistinguishable from a paid
  -- Starter account. Existing databases need the migration in ./migrations/0001-nullable-plan.sql.
  plan text check (plan in ('Starter', 'Pro', 'Elite')),

  -- Timestamps are text, holding the exact ISO-8601 string `new Date().toISOString()` produced,
  -- rather than timestamptz. That is deliberate. The application compares and sorts these as
  -- strings, and `subscribed_until` is a plain IST calendar date ("2026-08-11") compared against
  -- `todayIST()` with >=. Handing them to Postgres as timestamps means PostgREST returns them in
  -- its own format ("2026-08-11T00:00:00+00:00"), and those comparisons quietly stop agreeing with
  -- the ones the JSON backend makes. Text keeps the two backends byte-identical, which is the
  -- property that lets you develop against one and deploy against the other.
  -- ISO-8601 UTC sorts lexically in chronological order, so ORDER BY still does the right thing.
  created_at text not null,

  -- Ten digits, no country code or separators. Null on accounts created before the field existed.
  mobile text,

  role text not null default 'user' check (role in ('admin', 'user')),

  trial_started_at text,
  subscribed_until text,
  last_payment_id text,

  email_verified_at text,
  verification_token text,
  verification_sent_at text
);

-- Sign-in looks an account up by address on every attempt. The unique constraint above already
-- creates an index, so there is nothing further to add for that path.

-- Verification links are looked up by token, and the UPDATE that spends one is filtered on it.
-- Partial, because every verified account has a null here and there is no reason to index those.
create index if not exists users_verification_token_idx
  on public.users (verification_token)
  where verification_token is not null;

-- The admin dashboard lists newest first.
create index if not exists users_created_at_idx on public.users (created_at desc);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
--
-- This is the part that matters most, so read it before changing it.
--
-- A Supabase project's anon key is public by design — it is shipped in the browser bundle of any
-- app that uses one, and anyone can read it. PostgREST exposes every table to that key unless RLS
-- says otherwise. This table holds password hashes and live verification tokens.
--
-- So: RLS is enabled and NO policy is created. That combination denies everything to `anon` and
-- `authenticated`. The service_role key bypasses RLS entirely, and it is the only key the server
-- uses (SUPABASE_SERVICE_ROLE_KEY, never exposed to the browser, never NEXT_PUBLIC_).
--
-- Do not "fix" the fact that this table is unreadable from the client by adding a permissive
-- policy. Nothing in this application reads it from the client; every account read goes through a
-- route handler.

alter table public.users enable row level security;

-- Belt and braces: revoke the grants PostgREST's roles get by default, so the table is closed even
-- if RLS is later switched off by accident.
revoke all on public.users from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Product analytics
-- ---------------------------------------------------------------------------
--
-- One row per thing that happened: a page view, a sign-in, a sign-up, or an AI feature being
-- opened. `app/lib/analytics.ts` writes it and `app/lib/analytics-report.ts` reads it back into the
-- figures on the super admin dashboard.
--
-- Note what is NOT here: no name, no email address, no mobile number, no IP address, no full
-- referring URL and no query strings. An event carries a user id, and the dashboard joins the
-- personal columns from `public.users` at the moment it renders. That way a deleted account takes
-- its personal data with it, and this table never becomes a second, forgotten copy of it.

create table if not exists public.analytics_events (
  -- Generated by the application (`evt_<base36 time>_<random>`), like the user id, so the two
  -- backends mint ids the same way and a row written by one is the row the other would have written.
  id text primary key,

  -- 'visit' | 'signin' | 'signup' | 'feature' | 'action'. Constrained here as well as in
  -- TypeScript: this is the column every aggregate branches on, and an unrecognised value would
  -- silently be counted as nothing at all.
  type text not null check (type in ('visit', 'signin', 'signup', 'feature', 'action')),

  -- The exact instant, ISO-8601 UTC, as text — for the same reason `users.created_at` is text.
  -- The application sorts and compares these as strings, and letting Postgres reformat them makes
  -- the Supabase backend disagree with the JSON one. ISO-8601 UTC sorts lexically in chronological
  -- order, so `order by at desc` still means "newest first".
  at text not null,

  -- The IST calendar date `at` falls on ("2026-08-12"). Stored rather than derived because every
  -- query here is "since this day" and every aggregate groups by it — computing it per row per
  -- query would turn the index below into a sequential scan.
  day text not null,

  -- The account, when there was one. No foreign key: deleting an account must not delete the
  -- history of a day's traffic, and the dashboard already renders an id it cannot resolve as
  -- "Visitor (not signed in)".
  user_id text,

  -- A random id the browser mints and keeps, so a signed-out person browsing five pages is one
  -- visitor rather than five. Identifies nobody and is not a fingerprint.
  visitor_id text,

  -- A random per-tab id, so a run of rows can be read back as one sitting. Without it "sessions"
  -- and "pages per session" are not answerable: somebody who came back three times in a day is
  -- indistinguishable from three page views.
  session_id text,

  -- The AI feature key, on 'feature' rows. Not constrained to a list: the list lives in
  -- app/lib/plan-tiers.ts and adding a feature there should not need a migration here. The writer
  -- rejects unknown keys, and the report ignores any that survive.
  feature text,

  -- What the reader did, on 'action' rows: one of the keys of ACTIONS in app/lib/analytics.ts.
  -- Deliberately not constrained here for the same reason as `feature` — the closed list belongs
  -- in the application, which is what enforces it, and adding a product event should not need a
  -- migration.
  action text,

  -- What they did it to: a ticker, a section id, a plan name. Matched against a fixed alphabet on
  -- the way in, so it can never carry what somebody typed into a form.
  label text,

  -- Path only, query string already stripped by the writer.
  path text,

  -- The referring host, never the full URL.
  referrer text,

  device text,

  -- True when a 'feature' row was a refusal rather than an open. Kept because the features people
  -- are turned away from are the clearest measure of what the paywall is holding back.
  blocked boolean not null default false
);

-- Every read is "everything since day X, newest first", which is exactly this index.
create index if not exists analytics_events_day_idx on public.analytics_events (day desc, at desc);

-- The engagement table groups by account.
create index if not exists analytics_events_user_idx
  on public.analytics_events (user_id)
  where user_id is not null;

-- Same rule as `users`, and for a stronger reason than it looks: this table can be used to work
-- out who was on the site and when. RLS on, no policies, service_role only.
alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from anon, authenticated;

-- Retention. The dashboard looks back at most ANALYTICS_RETENTION_DAYS (120) days, and nothing in
-- the product asks a question about last year. Run this occasionally — or schedule it with pg_cron
-- if the project has it — so the table stays bounded by the window rather than by uptime:
--
--   delete from public.analytics_events where day < to_char(now() - interval '120 days', 'YYYY-MM-DD');

-- ---------------------------------------------------------------------------
-- Live sessions
-- ---------------------------------------------------------------------------
--
-- One row per open tab, rewritten in place while somebody is looking at it. `app/lib/presence.ts`
-- writes it from a heartbeat and the Live Users page of the super admin dashboard reads it.
--
-- Deliberately not part of `analytics_events`, which is an append-only log. Presence needs a signal
-- that repeats while nothing is happening — a person reading one page for twenty minutes emits no
-- events at all — and putting a once-a-minute-per-tab beat into the event log would multiply that
-- table by traffic-hours while telling the reports nothing they do not already know.
--
-- This table does not grow with traffic. A heartbeat is an upsert on `key`, so an hour-long sitting
-- is one row rewritten sixty times rather than sixty rows, and anything past the retention window
-- is deleted as the table is read. Its size is bounded by *concurrent* readers.

create table if not exists public.live_sessions (
  -- The tab, namespaced by what identified it: `s:` for a per-tab id, `v:` for a per-browser one,
  -- `u:` for an account with neither (a browser with no storage at all). Namespaced so a session
  -- id can never collide with a visitor id that happens to read the same.
  key text primary key,

  -- The account, when the sitting is signed in. No foreign key, for the same reason
  -- `analytics_events` has none: the account store has two backends and only one of them is this
  -- database, so the constraint would hold in production and not in development.
  user_id text,

  -- The same random per-browser id the visit tracker mints. Identifies nobody.
  visitor_id text,
  session_id text,

  -- The page the last heartbeat came from. Path only — the query string is stripped by the writer,
  -- because that is where the personal data is (a search term, a referral code, a verification
  -- token) and none of it is needed to say which page somebody is on.
  path text,

  device text,

  -- When this sitting was first seen. Defaulted here rather than sent by the application on
  -- purpose: PostgREST builds the `do update set` of an upsert from the keys it is given, so
  -- leaving this column out of the payload is exactly what stops a heartbeat from resetting the
  -- start of a sitting every minute. Text in ISO-8601 UTC, like every other instant here, so both
  -- backends mint and compare them identically.
  started_at text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),

  -- The last heartbeat. Whether somebody is on the site is decided entirely on this.
  last_seen_at text not null
);

-- Every read is "seen since this instant", and the housekeeping delete is the same predicate.
create index if not exists live_sessions_last_seen_idx on public.live_sessions (last_seen_at desc);

-- Same rule as `analytics_events`, and for the same reason with the clock removed: this table says
-- who is on the site *right now* and what page they are reading. RLS on, no policies, service_role
-- only.
alter table public.live_sessions enable row level security;
revoke all on public.live_sessions from anon, authenticated;

-- Retention. The application deletes expired rows as it reads, so this is only needed if nobody
-- has opened the Live Users page for a while:
--
--   delete from public.live_sessions where last_seen_at < to_char(now() at time zone 'utc' - interval '1 hour', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');

-- ---------------------------------------------------------------------------
-- Portfolios
-- ---------------------------------------------------------------------------
--
-- One row per stock a reader holds or tracks. `app/lib/portfolio.ts` reads and writes it; the
-- Portfolio section of the dashboard renders it against live prices.
--
-- This is on the server rather than in the browser on purpose. The watchlist card keeps its list
-- in localStorage, and losing it costs a minute of retyping; a portfolio records what somebody
-- actually paid, and it has to survive a new phone, a cleared cache and a second browser.

create table if not exists public.portfolio_holdings (
  -- Generated by the application (`hold_<base36 time>_<random>`), like every other id here.
  id text primary key,

  -- The owner. No foreign key, for the same reason `analytics_events` has none: the account store
  -- has two backends and only one of them is this database, so the constraint would hold in
  -- production and not in development — and a constraint that is only sometimes true is worse than
  -- none. The route scopes every read and write to the id in the caller's session token.
  user_id text not null,

  -- Upper-cased ticker: letters, digits and the `&`/`-` that ARE&M and BAJAJ-AUTO carry.
  symbol text not null,

  -- Units held. Zero is meaningful and allowed: it means tracked-but-not-owned, a candidate rather
  -- than a position, which is half of what a portfolio page is used for.
  quantity numeric not null default 0 check (quantity >= 0),

  -- Average buy price per unit, in rupees. Zero alongside a zero quantity is the tracked case.
  avg_price numeric not null default 0 check (avg_price >= 0),

  -- The reader's own target, or null. Drives the progress bar on the card.
  target_price numeric check (target_price >= 0),

  -- A line of their own reasoning, so a position still makes sense to them in six months.
  note text,

  added_at text not null,
  updated_at text not null,

  -- One row per stock per person, enforced here rather than by a read-then-insert: adding the same
  -- symbol from two tabs at once would pass a check in both and leave two rows for one holding.
  -- The store POSTs with `on_conflict=user_id,symbol` and `Prefer: resolution=merge-duplicates`,
  -- so a second add is a top-up rather than an error — and this constraint is what makes it one.
  unique (user_id, symbol)
);

-- Every read is "this account's holdings, newest first".
create index if not exists portfolio_holdings_user_idx on public.portfolio_holdings (user_id, added_at desc);

-- Same rule as the other two tables. This one names what a person owns and what they paid for it,
-- which is about as sensitive as anything in the app. RLS on, no policies, service_role only —
-- every read goes through a route handler that has already resolved the owner from their session.
alter table public.portfolio_holdings enable row level security;
revoke all on public.portfolio_holdings from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Feature locks
-- ---------------------------------------------------------------------------
--
-- The admin switch behind each AI surface. One row per locked feature.
--
-- This one is a fix rather than an addition: before it, locks lived in
-- `app/data/feature-locks.json`, which cannot work in production. A serverless host's application
-- directory is read-only, so the toggle failed silently; anywhere else, the next deploy wiped it.
-- An admin turning a feature off and finding it on again an hour later was that bug.
--
-- Only locked features are stored. An absent row means open, which is what a feature added to
-- `AI_FEATURES` tomorrow should be without anybody having to write a row for it.

create table if not exists public.feature_locks (
  -- The AI_FEATURES key from app/lib/plan-tiers.ts. Not constrained to a list here: that list is
  -- the application's, and adding a feature should not need a migration.
  feature text primary key,
  locked boolean not null default true,
  updated_at text not null
);

alter table public.feature_locks enable row level security;
revoke all on public.feature_locks from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Subscription payments
-- ---------------------------------------------------------------------------
--
-- One row per payment Razorpay confirmed. The account's *current* entitlement stays on
-- `users.subscribed_until` — that is what every paywall check reads, and it must not become a
-- query across a ledger. This is the ledger: what was bought, for how much, by whom, and when.
--
-- Why it exists at all: before it, a payment left exactly two traces — a date on the user row and
-- whatever Razorpay's own dashboard kept. Neither can answer "what did we bill this month", and
-- neither survives a refund being argued about.

create table if not exists public.subscription_payments (
  -- Razorpay's payment id, which is what makes this table idempotent: the verify route and the
  -- webhook both fire for one successful payment, and the second insert collides rather than
  -- writing a duplicate row. `users.last_payment_id` guards the entitlement the same way.
  payment_id text primary key,

  -- Razorpay's order id, so a payment can be traced back to the checkout that started it.
  order_id text,

  user_id text not null,

  -- 'Starter' | 'Pro' | 'Elite', as sold. Text rather than a check constraint against the plan
  -- list, because a plan renamed in the price list must not invalidate what was already charged.
  plan text not null,

  -- 'monthly' | 'annual'.
  cycle text not null,

  -- Paise, exactly as Razorpay counts it. Integer, never a float: money in a float is a rounding
  -- error waiting for a large enough number.
  amount_paise bigint not null check (amount_paise >= 0),
  currency text not null default 'INR',

  -- The promo or referral code applied, when there was one — how a discount campaign is measured.
  promo_code text,
  referral_code text,

  -- The IST date the subscription then ran to, so the ledger says what the money bought.
  subscribed_until text,

  paid_at text not null
);

-- "This account's payments, newest first" is the only read.
create index if not exists subscription_payments_user_idx on public.subscription_payments (user_id, paid_at desc);

alter table public.subscription_payments enable row level security;
revoke all on public.subscription_payments from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Client reviews
-- ---------------------------------------------------------------------------
--
-- The testimonials on the landing page, uploaded by an admin.
--
-- Provisioned here, and NOT yet read by the application: `app/lib/client-reviews.ts` still keeps
-- them in `app/data/client-reviews.json` with the profile images under `public/uploads/`. Moving
-- the rows is the easy half; the images need object storage (Supabase Storage) rather than a
-- column, because a serverless host cannot write to `public/` either. The table is here so the
-- schema is complete and the migration has somewhere to land — see the README.

create table if not exists public.client_reviews (
  id text primary key,
  name text not null,
  role text,
  comment text not null,
  rating integer not null check (rating between 1 and 5),
  -- URLs, not bytes. Whatever store the images end up in, this holds the address of one.
  image_url text,
  signature_url text,
  created_at text not null
);

create index if not exists client_reviews_created_at_idx on public.client_reviews (created_at desc);

alter table public.client_reviews enable row level security;
revoke all on public.client_reviews from anon, authenticated;

-- ---------------------------------------------------------------------------
-- The stock catalogue
-- ---------------------------------------------------------------------------
--
-- Every listed company, by symbol, name, scrip code and ISIN — what the directory and every stock
-- picker search against.
--
-- Provisioned here, and NOT yet read by the application: the catalogue is built by
-- `scripts/build-catalogue.mjs` from the exchange's own scrip master into `app/data/`, and it is
-- read from there. That is deliberate and not a bug — the catalogue is derived reference data, it
-- ships with the build, and reading ~4,950 rows from a bundled file is faster than querying for
-- them on every search. The table is here for a deployment that would rather keep it in Postgres
-- and refresh it without a redeploy.

create table if not exists public.stocks (
  -- The exchange ticker, upper-cased. The same key `portfolio_holdings.symbol` uses.
  symbol text primary key,
  name text not null,
  -- BSE's numeric scrip code, as text — it is an identifier, not a quantity, and some carry
  -- leading zeroes that a number would eat.
  scrip_code text,
  isin text,
  sector text,
  -- 'Large' | 'Mid' | 'Small', as classified by the catalogue build.
  cap_tier text,
  -- Used to fetch the company's logo.
  domain text,
  updated_at text not null
);

create index if not exists stocks_name_idx on public.stocks (lower(name));
create index if not exists stocks_isin_idx on public.stocks (isin) where isin is not null;

-- Unlike every other table here, this one holds no personal data at all — it is a public list of
-- listed companies. RLS is still enabled with no policies, because nothing in this application
-- reads it from the browser and a table that is open "because it is harmless" is one policy change
-- away from being the pattern somebody copies onto a table that is not.
alter table public.stocks enable row level security;
revoke all on public.stocks from anon, authenticated;

-- ---------------------------------------------------------------------------
-- ai_calls
-- ---------------------------------------------------------------------------
--
-- One row per model call: what was asked, how long it took, what it consumed and — the point of
-- the table — whether the reader ended up with a written read or the composed one.
--
-- The application does not need this table to observe itself. `app/lib/ai-telemetry.ts` always
-- keeps the last couple of thousand calls in the process's own memory, so the AI Operations panel
-- works on a fresh clone and on a deployment that has never applied this file. What that store
-- cannot do is survive a restart, and on a serverless host it cannot see the calls the *other*
-- instances made — which is exactly the deployment where an operator most needs the figures. This
-- table is the durable half, and the panel says which of the two it is reading.
--
-- Writes are fire-and-forget and a missing table latches the writer off after one attempt, so
-- never applying this costs the history and nothing else.

create table if not exists public.ai_calls (
  -- Generated by the application (`ai_<base36 time>_<random>`), like every other id here, so the
  -- two stores mint ids the same way.
  id text primary key,

  -- The exact instant, ISO-8601 UTC, as text — for the same reason `analytics_events.at` is text.
  -- ISO-8601 UTC sorts lexically in chronological order, so `order by at desc` is "newest first".
  at text not null,

  -- The IST calendar date `at` falls on. Stored rather than derived because every query here is
  -- "since this day" and every aggregate groups by it.
  day text not null,

  -- Which call site asked: 'board-read', 'intel-search', 'stock-analysis' and so on. Deliberately
  -- not constrained to a list — these name call sites in the code, and adding one should not need
  -- a migration. The report groups by whatever it finds.
  feature text not null,

  -- The model asked for, or null when nothing was attempted (no key configured).
  model text,

  -- What the reader ended up with. Constrained here as well as in TypeScript: this is the column
  -- every aggregate branches on, and an unrecognised value would be counted as nothing at all.
  --   'ok'           the model answered and the answer was usable
  --   'unusable'     it answered, but the reply could not be used — the reader got the composed read
  --   'failed'       non-2xx, a network error, or the timeout
  --   'unconfigured' no API key; nothing was attempted and nothing was spent
  outcome text not null check (outcome in ('ok', 'unusable', 'failed', 'unconfigured')),

  -- The HTTP status, when there was a response. Null for a timeout, a network error, or no key.
  status integer,

  -- Wall-clock duration in milliseconds, including the network. Null when nothing was attempted.
  -- For a streamed call this is time to the end of the stream, not to the first token.
  ms integer,

  -- Tokens as OpenRouter reported them, and what it said the call cost in USD. All three are
  -- nullable rather than defaulting to zero: a failed call reports no usage, and a zero would be
  -- indistinguishable from a call that genuinely consumed nothing. Cost is read from the reply
  -- rather than estimated from a price table, which would be wrong the first time a model is
  -- repriced and nobody would notice.
  prompt_tokens integer,
  completion_tokens integer,
  cost_usd double precision,

  streamed boolean not null default false,

  -- The failure message, clipped by the writer. Never a request or response body: a completion's
  -- body can contain the prompt, and a prompt can contain whatever a reader typed into the search.
  error text
);

-- Every read is "since this day, newest first".
create index if not exists ai_calls_day_idx on public.ai_calls (day, at desc);

-- Nothing in this application reads this table from the browser — the panel goes through
-- `/api/admin/ai-usage`, which re-checks the caller is an admin — so the anon and authenticated
-- roles get nothing, as with every other table here.
alter table public.ai_calls enable row level security;
revoke all on public.ai_calls from anon, authenticated;
