import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { AiStockCompare } from "../../app/components/ai-stock-compare";

function mockFetchOnce(ok: boolean, data?: unknown) {
  (global.fetch as jest.Mock).mockResolvedValueOnce({
    ok,
    json: () => Promise.resolve(data),
  });
}

const baseResult = {
  stockA: "TCS",
  stockB: "INFY",
  winner: "A" as const,
  verdict: "TCS looks stronger right now.",
  stockAPros: ["Strong margins"],
  stockACons: ["Rich valuation"],
  stockBPros: ["Diversified clients"],
  stockBCons: ["Slower growth"],
  stockAScore: 80,
  stockBScore: 70,
  source: "ai" as const,
};

describe("AiStockCompare", () => {
  beforeEach(() => {
    global.fetch = jest.fn();
  });

  it("renders the default inputs and no result initially", () => {
    render(<AiStockCompare />);
    expect(screen.getByPlaceholderText("Stock A, e.g. TCS")).toHaveValue("TCS");
    expect(screen.getByPlaceholderText("Stock B, e.g. INFY")).toHaveValue("INFY");
    expect(screen.getByRole("button", { name: "Compare with AI" })).toBeInTheDocument();
  });

  it("does not submit when stock A is blank", async () => {
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.clear(screen.getByPlaceholderText("Stock A, e.g. TCS"));
    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    expect(global.fetch).not.toHaveBeenCalled();
  });

  it("does not submit when stock B is blank (whitespace only)", async () => {
    const user = userEvent.setup();
    render(<AiStockCompare />);

    const stockB = screen.getByPlaceholderText("Stock B, e.g. INFY");
    await user.clear(stockB);
    await user.type(stockB, "   ");
    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    expect(global.fetch).not.toHaveBeenCalled();
  });

  it("shows a loading label and posts the two symbols on submit", async () => {
    let resolveFetch: (value: unknown) => void = () => {};
    (global.fetch as jest.Mock).mockReturnValueOnce(
      new Promise((resolve) => {
        resolveFetch = resolve;
      })
    );
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    expect(screen.getByRole("button", { name: "Comparing..." })).toBeInTheDocument();
    expect(global.fetch).toHaveBeenCalledWith(
      "/api/compare",
      expect.objectContaining({
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ stockA: "TCS", stockB: "INFY" }),
      })
    );

    resolveFetch({ ok: true, json: () => Promise.resolve(baseResult) });
    await waitFor(() => expect(screen.getByRole("button", { name: "Compare with AI" })).toBeInTheDocument());
  });

  it("renders the winner-A verdict, scores, pros/cons, and 'Generated by AI agent' provenance", async () => {
    mockFetchOnce(true, baseResult);
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    await waitFor(() => expect(screen.getByText("TCS looks stronger right now.")).toBeInTheDocument());
    // "TCS" appears both as the winner-verdict badge and the stockA card heading.
    expect(screen.getAllByText("TCS").length).toBeGreaterThanOrEqual(2);
    expect(screen.getByText("Score 80/100")).toBeInTheDocument();
    expect(screen.getByText("Score 70/100")).toBeInTheDocument();
    expect(screen.getByText("Strong margins")).toBeInTheDocument();
    expect(screen.getByText("Rich valuation")).toBeInTheDocument();
    expect(screen.getByText("Diversified clients")).toBeInTheDocument();
    expect(screen.getByText("Slower growth")).toBeInTheDocument();
    expect(screen.getByText(/Generated by AI agent/)).toBeInTheDocument();
  });

  it("renders the winner-B verdict label", async () => {
    mockFetchOnce(true, { ...baseResult, winner: "B" as const });
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    await waitFor(() => expect(screen.getByText("INFY", { selector: "span" })).toBeInTheDocument());
  });

  it("renders 'Too close to call' for a Tie, and the heuristic-demo provenance line", async () => {
    mockFetchOnce(true, { ...baseResult, winner: "Tie" as const, source: "demo" as const });
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    await waitFor(() => expect(screen.getByText("Too close to call")).toBeInTheDocument());
    expect(screen.getByText(/Heuristic demo \(no AI key configured\)/)).toBeInTheDocument();
  });

  it("shows 'No points returned.' when a pros/cons list is empty", async () => {
    mockFetchOnce(true, { ...baseResult, stockAPros: [], stockACons: [], stockBPros: [], stockBCons: [] });
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    await waitFor(() => expect(screen.getAllByText("No points returned.")).toHaveLength(4));
  });

  it("shows an error message when the response is not ok", async () => {
    mockFetchOnce(false);
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    await waitFor(() =>
      expect(screen.getByText("Couldn't run the comparison right now. Please try again shortly.")).toBeInTheDocument()
    );
  });

  it("shows an error message when fetch rejects", async () => {
    (global.fetch as jest.Mock).mockRejectedValueOnce(new Error("network down"));
    const user = userEvent.setup();
    render(<AiStockCompare />);

    await user.click(screen.getByRole("button", { name: "Compare with AI" }));

    await waitFor(() =>
      expect(screen.getByText("Couldn't run the comparison right now. Please try again shortly.")).toBeInTheDocument()
    );
  });

  it("lets the user retype both stock symbols before submitting", async () => {
    mockFetchOnce(true, baseResult);
    const user = userEvent.setup();
    render(<AiStockCompare />);

    const stockA = screen.getByPlaceholderText("Stock A, e.g. TCS");
    const stockB = screen.getByPlaceholderText("Stock B, e.g. INFY");
    await user.clear(stockA);
    await user.type(stockA, "RELIANCE");
    await user.clear(stockB);
    await user.type(stockB, "ONGC");

    fireEvent.submit(stockA.closest("form") as HTMLFormElement);

    await waitFor(() =>
      expect(global.fetch).toHaveBeenCalledWith(
        "/api/compare",
        expect.objectContaining({ body: JSON.stringify({ stockA: "RELIANCE", stockB: "ONGC" }) })
      )
    );
  });
});
