import { render, screen, fireEvent, within, act } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { BuyTomorrowPicks } from "../../app/components/buy-tomorrow-picks";

jest.mock("../../app/components/ai-report-modal", () => ({
  AiReportModal: (props: any) => (
    <div
      data-testid="ai-report-modal"
      data-open={String(props.open)}
      data-symbol={props.analysis?.stock ?? ""}
      data-logo={props.logoUrl ?? ""}
      data-company={props.companyName ?? ""}
      data-loading={String(props.loading)}
    >
      <button data-testid="modal-close" onClick={props.onClose}>
        close
      </button>
    </div>
  ),
}));

function deferred<T>() {
  let resolve!: (value: T) => void;
  const promise = new Promise<T>((res) => {
    resolve = res;
  });
  return { promise, resolve };
}

const basePicks = [
  {
    symbol: "AAA",
    name: "Alpha Co",
    sector: "Information Technology",
    businessType: "Software services",
    logo: "https://logo.test/a.png",
    capTier: "Large",
    price: 100.5,
    changePercent: 2.5,
    oneMonthReturn: 5,
    outlook: "Bullish",
    confidence: 80,
    newsSignal: "Positive news flow",
    priceSignal: "Trading below 20-day average",
    institutionalTag: "Government / PSU",
    institutionalSignal: "Strong PSU interest",
  },
  {
    symbol: "BBB",
    name: "Beta Co",
    sector: "Banking",
    businessType: "Private bank",
    logo: "https://logo.test/b.png",
    capTier: "Mid",
    price: null,
    changePercent: null,
    oneMonthReturn: -2,
    outlook: "Bullish",
    confidence: 60,
    newsSignal: "Mixed signals",
    priceSignal: "Cheaper than last week",
    institutionalTag: "FII & DII favourite",
    institutionalSignal: "FII buying",
  },
  {
    symbol: "CCC",
    name: "Gamma Co",
    sector: "Pharmaceuticals",
    businessType: "Generics",
    logo: "https://logo.test/c.png",
    capTier: "Small",
    price: 50,
    changePercent: -1.2,
    oneMonthReturn: 1,
    outlook: "Bullish",
    confidence: 50,
    newsSignal: "Neutral coverage",
    priceSignal: "Range bound",
    institutionalTag: "Retail favourite",
    institutionalSignal: "Retail interest picking up",
  },
];

function mockListFetch(response: unknown, ok = true) {
  global.fetch = jest.fn().mockResolvedValue({
    ok,
    json: async () => response,
  } as Response);
}

describe("BuyTomorrowPicks", () => {
  it("shows loading skeletons before data arrives", () => {
    global.fetch = jest.fn(() => new Promise(() => {})) as unknown as typeof fetch;
    const { container } = render(<BuyTomorrowPicks />);
    expect(screen.getByText("Loading…")).toBeInTheDocument();
    expect(container.querySelectorAll(".animate-pulse")).toHaveLength(9);
  });

  it("renders picks covering institutional tag, price and change branches", async () => {
    mockListFetch({ date: "2026-08-04", generatedAt: "", source: "ai", picks: basePicks });
    render(<BuyTomorrowPicks />);

    expect(await screen.findByText("AAA")).toBeInTheDocument();
    expect(screen.getByText("Generated by AI agent")).toBeInTheDocument();

    const aaaCard = screen.getByText("AAA").closest("button")!;
    expect(within(aaaCard).getByText("₹100.50")).toBeInTheDocument();
    expect(within(aaaCard).getByText("▲ 2.50%")).toBeInTheDocument();

    const bbbCard = screen.getByText("BBB").closest("button")!;
    expect(within(bbbCard).getAllByText("—")).toHaveLength(2);

    const cccCard = screen.getByText("CCC").closest("button")!;
    expect(within(cccCard).getByText("▼ 1.20%")).toBeInTheDocument();

    // institutionalTagClass: all three branches
    expect(screen.getByText("Government / PSU")).toBeInTheDocument();
    expect(screen.getByText("FII & DII favourite")).toBeInTheDocument();
    expect(screen.getByText("Retail favourite")).toBeInTheDocument();

    expect(within(aaaCard).getByText(/News:/)).toBeInTheDocument();
    expect(within(aaaCard).getByText(/Positive news flow/)).toBeInTheDocument();
  });

  it("shows heuristic source label", async () => {
    mockListFetch({ date: "2026-08-04", generatedAt: "", source: "heuristic", picks: [] });
    render(<BuyTomorrowPicks />);
    expect(await screen.findByText("Heuristic demo (no AI key configured)")).toBeInTheDocument();
  });

  it("shows an error banner when the response is not ok", async () => {
    mockListFetch({}, false);
    render(<BuyTomorrowPicks />);
    expect(await screen.findByText(/Couldn't reach the AI screening engine/)).toBeInTheDocument();
  });

  it("shows an error banner when the fetch rejects", async () => {
    global.fetch = jest.fn().mockRejectedValue(new Error("network down"));
    render(<BuyTomorrowPicks />);
    expect(await screen.findByText(/Couldn't reach the AI screening engine/)).toBeInTheDocument();
  });

  it("shows the empty state when there are no picks and no error", async () => {
    mockListFetch({ date: "2026-08-04", generatedAt: "", source: "ai", picks: [] });
    render(<BuyTomorrowPicks />);
    expect(await screen.findByText("No picks available right now.")).toBeInTheDocument();
  });

  it("falls back to initials when the logo image fails to load", async () => {
    mockListFetch({ date: "2026-08-04", generatedAt: "", source: "ai", picks: [basePicks[0]] });
    render(<BuyTomorrowPicks />);
    const img = await screen.findByAltText("Alpha Co logo");
    fireEvent.error(img);
    expect(screen.getByText("A")).toBeInTheDocument();
  });

  it("selects a pick, shows loading then the analysis in the modal, and closes it", async () => {
    const user = userEvent.setup();
    const research = deferred<Response>();
    global.fetch = jest.fn((url: any) => {
      if (String(url).includes("/api/research")) return research.promise;
      return Promise.resolve({
        ok: true,
        json: async () => ({ date: "2026-08-04", generatedAt: "", source: "ai", picks: basePicks }),
      } as Response);
    }) as unknown as typeof fetch;

    render(<BuyTomorrowPicks />);
    await screen.findByText("AAA");

    const aaaCard = screen.getByText("AAA").closest("button")!;
    await user.click(aaaCard);

    let modal = screen.getByTestId("ai-report-modal");
    expect(modal).toHaveAttribute("data-open", "true");
    expect(modal).toHaveAttribute("data-loading", "true");
    expect(modal).toHaveAttribute("data-logo", "https://logo.test/a.png");
    expect(modal).toHaveAttribute("data-company", "Alpha Co");

    await act(async () => {
      research.resolve({ ok: true, json: async () => ({ stock: "AAA", score: 80 }) } as Response);
      await research.promise;
    });

    modal = screen.getByTestId("ai-report-modal");
    expect(modal).toHaveAttribute("data-loading", "false");
    expect(modal).toHaveAttribute("data-symbol", "AAA");

    await user.click(screen.getByTestId("modal-close"));
    expect(screen.getByTestId("ai-report-modal")).toHaveAttribute("data-open", "false");
  });
});
