// The slide for an AI feature that has no bespoke live scene.
//
// Fourteen of the eighteen features are in this position, so this component is most of what the
// slider now shows. What matters about it is that it reads as a product shot rather than a
// placeholder — it names the feature, says which plan carries it, shows the shape of the board it
// produces, and is honest that the figures in that mock are illustrative.

import { render, screen, within } from "@testing-library/react";
import { HeroFeatureScene } from "../../app/components/hero-feature-scene";
import { featureShot } from "../../app/lib/feature-shots";
import { FEATURE_SHOWCASES, LIVE_SHOWCASES, type HeroShowcase } from "../../app/lib/hero-rotation";

// The manifest is generated by `scripts/capture-feature-shots.mjs` and ships empty, so the real
// module answers null for everything. Mocked here so both halves — with a captured picture and
// without one — can be driven from the suite rather than depending on whether somebody has run the
// capture script on this clone.
jest.mock("../../app/lib/feature-shots", () => ({ featureShot: jest.fn(() => null) }));

const shotFor = featureShot as jest.MockedFunction<typeof featureShot>;

const SHOT = {
  src: "/feature-shots/market-pulse.png",
  width: 1400,
  height: 620,
  capturedAt: "2026-08-15T09:00:00.000Z",
};

beforeEach(() => {
  shotFor.mockReturnValue(null);
});

function showcaseFor(key: string): HeroShowcase {
  return FEATURE_SHOWCASES.find((entry) => entry.key === key)!;
}

const MARKET_PULSE = showcaseFor("market-pulse");
const BUY_TOMORROW = showcaseFor("buy-tomorrow");
const INTEL = showcaseFor("intel");
const DIVIDENDS = showcaseFor("dividends");

describe("HeroFeatureScene", () => {
  it("names the feature, its plan and what it does", () => {
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    expect(screen.getByText("The session's mood, read off the whole tape")).toBeInTheDocument();
    expect(screen.getByText("Starter plan")).toBeInTheDocument();
    expect(screen.getByText("AI market pulse")).toBeInTheDocument();
    expect(screen.getByText(MARKET_PULSE.blurb)).toBeInTheDocument();
  });

  it("lists what the feature actually does", () => {
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    for (const point of MARKET_PULSE.points ?? []) {
      expect(screen.getByText(point)).toBeInTheDocument();
    }
  });

  it("sends a reader straight to the feature", () => {
    render(<HeroFeatureScene showcase={INTEL} />);

    const link = screen.getByRole("link", { name: /Open AI intelligence search/ });
    expect(link).toHaveAttribute("href", "/intelligence-search");
  });

  it("draws the shape of the board the feature produces", () => {
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    const table = screen.getByRole("table", { name: /An illustration of the AI market pulse board/ });
    expect(within(table).getByText("Index")).toBeInTheDocument();
    expect(within(table).getByText("S&P BSE SENSEX")).toBeInTheDocument();
    expect(within(table).getByText("81,204")).toBeInTheDocument();
  });

  it("colours a gain green and a fall red", () => {
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    expect(screen.getByText("+1.14%").className).toContain("text-emerald-600");
    expect(screen.getByText("−0.21%").className).toContain("text-rose-600");
  });

  it("leaves a cell that is not a direction uncoloured", () => {
    render(<HeroFeatureScene showcase={DIVIDENDS} />);

    // A payout is neither up nor down, and colouring it green would imply it was a gain.
    const payout = screen.getByText("₹6.25");
    expect(payout.className).not.toContain("text-emerald-600");
    expect(payout.className).not.toContain("text-rose-600");
  });

  it("says the figures in the mock are illustrative", () => {
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    // The one thing this component must never do is present invented numbers as measured ones.
    expect(screen.getByText(/the figures illustrate the layout/)).toBeInTheDocument();
  });

  // ---------------------------------------------------------------------------
  // The company marks
  // ---------------------------------------------------------------------------

  it("puts each company's own mark before its name", () => {
    render(<HeroFeatureScene showcase={showcaseFor("most-traded")} />);

    // The same CompanyLogo the boards use, so the ticker store's real image is fetched and a
    // company it has never heard of falls back to a drawn monogram rather than a broken frame.
    expect(screen.getByAltText(/\(RELIANCE\) logo$/)).toBeInTheDocument();
    expect(screen.getByAltText(/\(HDFCBANK\) logo$/)).toBeInTheDocument();
    expect(screen.getByAltText(/\(ICICIBANK\) logo$/)).toBeInTheDocument();
  });

  it("marks the row by its company even when the stock is not the first cell", () => {
    render(<HeroFeatureScene showcase={showcaseFor("news")} />);

    // On the news showcase the headline is on the left and the stock in the middle; the mark still
    // belongs at the front, where it says whose row this is.
    const row = screen.getByText("Margin guidance trimmed for H2").closest("tr")!;
    expect(within(row).getByAltText(/\(TECHM\) logo$/)).toBeInTheDocument();
  });

  it("puts no mark on a row that names no company", () => {
    const { container } = render(<HeroFeatureScene showcase={showcaseFor("sectors")} />);

    // A monogram tile for "Metal" would be a face put to something that has none.
    expect(container.querySelectorAll("img")).toHaveLength(0);
  });

  // ---------------------------------------------------------------------------
  // The screenshot
  // ---------------------------------------------------------------------------

  it("shows the real screenshot of the feature when one has been captured", () => {
    shotFor.mockReturnValue(SHOT);
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    const shot = screen.getByAltText("Screenshot of the AI market pulse board running in StockersAI");
    expect(shot).toHaveAttribute("loading", "lazy");
    expect(shot.getAttribute("src")).toContain(encodeURIComponent(SHOT.src));
  });

  it("keeps the drawn strip beside the screenshot", () => {
    shotFor.mockReturnValue(SHOT);
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    // The strip is where the marks and the column headings are legible at this size, which a
    // scaled-down board is not. Scoped to the table: the card's index rail names some of the same
    // indices along the top of every scene.
    const table = screen.getByRole("table");
    expect(within(table).getByText("81,204")).toBeInTheDocument();
    expect(within(table).getByText("Index")).toBeInTheDocument();
  });

  it("says which half of the card is a photograph and which is drawn", () => {
    shotFor.mockReturnValue(SHOT);
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    // Disclaiming the screenshot too would be as wrong as disclaiming neither.
    expect(screen.getByText(/The screenshot is this feature running in StockersAI/)).toBeInTheDocument();
    expect(screen.getByText(/the figures illustrate the layout/)).toBeInTheDocument();
  });

  it("shows no picture frame at all when nothing has been captured", () => {
    render(<HeroFeatureScene showcase={MARKET_PULSE} />);

    expect(screen.queryByAltText(/Screenshot of/)).not.toBeInTheDocument();
    expect(screen.queryByText(/The screenshot is this feature running/)).not.toBeInTheDocument();
  });

  it.each([
    ["starter", MARKET_PULSE, "Starter plan"],
    ["pro", BUY_TOMORROW, "Pro plan"],
    ["elite", INTEL, "Elite plan"],
  ])("badges a %s feature with its plan", (_tier, showcase, label) => {
    render(<HeroFeatureScene showcase={showcase as HeroShowcase} />);
    expect(screen.getByText(label)).toBeInTheDocument();
  });

  it("renders every feature showcase in the catalogue without falling over", () => {
    for (const showcase of FEATURE_SHOWCASES) {
      const { unmount } = render(<HeroFeatureScene showcase={showcase} />);
      expect(screen.getByText(showcase.title)).toBeInTheDocument();
      unmount();
    }
  });

  it("still renders a card for a showcase carrying no mock content", () => {
    // The live showcases have a bespoke scene instead of columns and rows. This component is not
    // asked for them, but it must degrade to an empty panel rather than throwing if it ever is.
    const live = LIVE_SHOWCASES[0];
    render(<HeroFeatureScene showcase={live} />);

    expect(screen.getByText(live.title)).toBeInTheDocument();
    expect(screen.getByRole("table")).toBeInTheDocument();
    expect(screen.queryAllByRole("row")).toHaveLength(1);
  });
});
