import { render, screen } from "@testing-library/react";
import { MarketPulse } from "../../app/components/market-pulse";

function mockFetch(response: unknown, ok = true) {
  global.fetch = jest.fn().mockResolvedValue({
    ok,
    json: async () => response,
  } as Response);
}

const baseState = {
  breadth: {
    totalTracked: 200,
    advancing: 120,
    declining: 70,
    unchanged: 10,
    averageChangePercent: 1.25,
    topSector: { name: "IT", averageChangePercent: 2.1 },
    bottomSector: { name: "Realty", averageChangePercent: -1.4 },
    topGainer: { symbol: "AAA", name: "Alpha Co", changePercent: 8.5 },
    topLoser: { symbol: "BBB", name: "Beta Co", changePercent: -6.2 },
    movers: {
      Large: {
        tracked: 60,
        gainers: [{ symbol: "LGAIN", name: "Large Gainer Ltd", sector: "Banking", capTier: "Large", price: 500, changePercent: 3.1 }],
        losers: [{ symbol: "LLOSE", name: "Large Loser Ltd", sector: "FMCG", capTier: "Large", price: 250, changePercent: -2.4 }],
      },
      Mid: { tracked: 90, gainers: [], losers: [] },
      Small: { tracked: 50, gainers: [], losers: [] },
    },
  },
  indices: [
    {
      symbol: "NIFTY50",
      name: "NIFTY 50",
      exchange: "NSE",
      description: "50 large caps across sectors",
      price: 24624.65,
      previousClose: 24614.9,
      change: 9.75,
      changePercent: 0.0396,
      dayHigh: 24677.6,
      dayLow: 24497.95,
      live: true,
      asOf: "2026-08-04T10:00:00.000Z",
    },
    {
      symbol: "SENSEX",
      name: "SENSEX",
      exchange: "BSE",
      description: "30 blue chips on the BSE",
      price: 78581,
      previousClose: 78428.95,
      change: 152.05,
      changePercent: 0.19,
      dayHigh: 79055.38,
      dayLow: 78285.74,
      live: true,
      asOf: "2026-08-04T10:00:00.000Z",
    },
    {
      symbol: "BANKNIFTY",
      name: "Bank NIFTY",
      exchange: "NSE",
      description: "12 most liquid banking stocks",
      price: 57739.95,
      previousClose: 57907.2,
      change: -167.25,
      changePercent: -0.29,
      dayHigh: 57931.85,
      dayLow: 57456.35,
      live: true,
      asOf: "2026-08-04T10:00:00.000Z",
    },
  ],
  mood: "Risk-On" as const,
  lastTradeAt: "2026-08-04T10:00:00.000Z",
  breadthAsOf: "2026-08-04T10:00:00.000Z",
  summary: "Markets are broadly positive today.",
  themes: ["AI capex boom", "Rate-cut hopes"],
  sectorsToWatch: ["Banking", "IT"],
  generatedAt: "2026-08-04T10:00:00.000Z",
  source: "ai" as const,
};

describe("MarketPulse", () => {
  it("shows a loading skeleton before data arrives", () => {
    global.fetch = jest.fn(() => new Promise(() => {})) as unknown as typeof fetch;
    const { container } = render(<MarketPulse />);
    expect(container.querySelector(".animate-pulse")).toBeInTheDocument();
  });

  it("renders full market pulse data: mood badge, breadth, gainer/loser, themes, sectors", async () => {
    mockFetch(baseState);
    render(<MarketPulse />);

    expect(await screen.findByText("Risk-On")).toBeInTheDocument();
    expect(screen.getByText("Markets are broadly positive today.")).toBeInTheDocument();
    expect(screen.getByText(/Generated by AI agent/)).toBeInTheDocument();
    expect(screen.getByText(/breadth across 200 stocks/)).toBeInTheDocument();

    // Advance/decline now reads off the live pulse bars.
    expect(screen.getByLabelText("120 stocks advancing, 70 declining")).toBeInTheDocument();
    expect(screen.getByText("120")).toBeInTheDocument();
    expect(screen.getByText("70")).toBeInTheDocument();
    expect(screen.getByText("10 flat")).toBeInTheDocument();

    expect(screen.getByText("+1.25%")).toBeInTheDocument();

    expect(screen.getByText("AAA")).toBeInTheDocument();
    expect(screen.getByText("▲ 8.50%")).toBeInTheDocument();
    expect(screen.getByText("BBB")).toBeInTheDocument();
    expect(screen.getByText("▼ 6.20%")).toBeInTheDocument();

    // Per-cap movers, defaulting to the Large cap tier.
    expect(screen.getByText("Top 5 gainers")).toBeInTheDocument();
    expect(screen.getByText("Top 5 losers")).toBeInTheDocument();
    expect(screen.getByText("LGAIN")).toBeInTheDocument();
    expect(screen.getByText("LLOSE")).toBeInTheDocument();
    expect(screen.getByText("Ranked within Large Cap · 60 stocks tracked")).toBeInTheDocument();

    // The three benchmarks, with their live level and today's move.
    expect(screen.getByText("Benchmark indices")).toBeInTheDocument();
    expect(screen.getByLabelText("NIFTY 50, 24,624.65, +0.04%")).toBeInTheDocument();
    expect(screen.getByLabelText("SENSEX, 78,581.00, +0.19%")).toBeInTheDocument();
    expect(screen.getByLabelText("Bank NIFTY, 57,739.95, -0.29%")).toBeInTheDocument();

    expect(screen.getByText("AI capex boom")).toBeInTheDocument();
    expect(screen.getByText("Rate-cut hopes")).toBeInTheDocument();
    expect(screen.getByText("Watch: Banking")).toBeInTheDocument();
    expect(screen.getByText("Watch: IT")).toBeInTheDocument();
  });

  it("renders the Neutral and Risk-Off moods, heuristic source, negative average move, and missing gainer/loser", async () => {
    mockFetch({
      ...baseState,
      mood: "Neutral",
      source: "heuristic",
      breadth: {
        ...baseState.breadth,
        advancing: 0,
        declining: 0,
        averageChangePercent: -0.4,
        topGainer: null,
        topLoser: null,
      },
      themes: ["Cautious sentiment"],
      sectorsToWatch: ["Pharma"],
    });
    render(<MarketPulse />);

    expect(await screen.findByText("Neutral")).toBeInTheDocument();
    expect(screen.getByText(/Heuristic \(no AI key configured\)/)).toBeInTheDocument();
    expect(screen.getByText("-0.40%")).toBeInTheDocument();
    // topGainer/topLoser null -> em dash fallback (two occurrences)
    expect(screen.getAllByText("—")).toHaveLength(2);
  });

  it("renders the Risk-Off mood", async () => {
    mockFetch({ ...baseState, mood: "Risk-Off" });
    render(<MarketPulse />);
    expect(await screen.findByText("Risk-Off")).toBeInTheDocument();
  });

  it("shows an error banner when the response is not ok", async () => {
    mockFetch({}, false);
    render(<MarketPulse />);
    expect(await screen.findByText(/Couldn't reach the market data feed/)).toBeInTheDocument();
  });

  it("shows an error banner when the fetch rejects", async () => {
    global.fetch = jest.fn().mockRejectedValue(new Error("network down"));
    render(<MarketPulse />);
    expect(await screen.findByText(/Couldn't reach the market data feed/)).toBeInTheDocument();
  });

  it("shows the generic unavailable message when the response succeeds but the body is null", async () => {
    mockFetch(null);
    render(<MarketPulse />);
    expect(await screen.findByText("Market pulse unavailable right now.")).toBeInTheDocument();
  });
});
