import { act, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MarketPulse, narrativeProvenance, topMovers } from "../../app/components/market-pulse";

function mockFetch(response: unknown, ok = true) {
  global.fetch = jest.fn().mockResolvedValue({
    ok,
    json: async () => response,
  } as Response);
}

const baseState = {
  breadth: {
    totalTracked: 200,
    advancing: 120,
    declining: 70,
    unchanged: 10,
    averageChangePercent: 1.25,
    topSector: { name: "IT", averageChangePercent: 2.1 },
    bottomSector: { name: "Realty", averageChangePercent: -1.4 },
    topGainer: { symbol: "AAA", name: "Alpha Co", changePercent: 8.5 },
    topLoser: { symbol: "BBB", name: "Beta Co", changePercent: -6.2 },
    movers: {
      Large: {
        tracked: 60,
        gainers: [{ symbol: "LGAIN", name: "Large Gainer Ltd", sector: "Banking", capTier: "Large", price: 500, changePercent: 3.1 }],
        losers: [{ symbol: "LLOSE", name: "Large Loser Ltd", sector: "FMCG", capTier: "Large", price: 250, changePercent: -2.4 }],
      },
      Mid: { tracked: 90, gainers: [], losers: [] },
      Small: { tracked: 50, gainers: [], losers: [] },
    },
  },
  indices: [
    {
      symbol: "NIFTY50",
      name: "NIFTY 50",
      exchange: "NSE",
      description: "50 large caps across sectors",
      price: 24624.65,
      previousClose: 24614.9,
      change: 9.75,
      changePercent: 0.0396,
      dayHigh: 24677.6,
      dayLow: 24497.95,
      live: true,
      asOf: "2026-08-04T10:00:00.000Z",
    },
    {
      symbol: "SENSEX",
      name: "SENSEX",
      exchange: "BSE",
      description: "30 blue chips on the BSE",
      price: 78581,
      previousClose: 78428.95,
      change: 152.05,
      changePercent: 0.19,
      dayHigh: 79055.38,
      dayLow: 78285.74,
      live: true,
      asOf: "2026-08-04T10:00:00.000Z",
    },
    {
      symbol: "BANKNIFTY",
      name: "Bank NIFTY",
      exchange: "NSE",
      description: "12 most liquid banking stocks",
      price: 57739.95,
      previousClose: 57907.2,
      change: -167.25,
      changePercent: -0.29,
      dayHigh: 57931.85,
      dayLow: 57456.35,
      live: true,
      asOf: "2026-08-04T10:00:00.000Z",
    },
  ],
  mood: "Risk-On" as const,
  lastTradeAt: "2026-08-04T10:00:00.000Z",
  breadthAsOf: "2026-08-04T10:00:00.000Z",
  summary: "Markets are broadly positive today.",
  themes: ["AI capex boom", "Rate-cut hopes"],
  sectorsToWatch: ["Banking", "IT"],
  generatedAt: "2026-08-04T10:00:00.000Z",
  source: "ai" as const,
};

describe("MarketPulse", () => {
  it("shows a loading skeleton before data arrives", () => {
    global.fetch = jest.fn(() => new Promise(() => {})) as unknown as typeof fetch;
    const { container } = render(<MarketPulse />);
    expect(container.querySelector(".animate-pulse")).toBeInTheDocument();
  });

  it("renders full market pulse data: mood badge, breadth, gainer/loser, themes, sectors", async () => {
    mockFetch(baseState);
    render(<MarketPulse />);

    expect(await screen.findByText("Risk-On")).toBeInTheDocument();
    expect(screen.getByText("Markets are broadly positive today.")).toBeInTheDocument();
    expect(screen.getByText(/Generated by AI agent/)).toBeInTheDocument();
    expect(screen.getByText(/breadth across 200 stocks/)).toBeInTheDocument();

    // Advance/decline now reads off the live pulse bars.
    expect(screen.getByLabelText("120 stocks advancing, 70 declining, 10 unchanged")).toBeInTheDocument();
    expect(screen.getByText("120")).toBeInTheDocument();
    expect(screen.getByText("70")).toBeInTheDocument();
    // The breadth panel now names the split, the reading behind it and the ratio.
    expect(screen.getByText("63.2%")).toBeInTheDocument();
    expect(screen.getByText("Advancers ahead")).toBeInTheDocument();
    expect(screen.getByText("1.71 : 1")).toBeInTheDocument();

    expect(screen.getByText("+1.25%")).toBeInTheDocument();

    expect(screen.getByText("AAA")).toBeInTheDocument();
    expect(screen.getByText("▲ 8.50%")).toBeInTheDocument();
    expect(screen.getByText("BBB")).toBeInTheDocument();
    expect(screen.getByText("▼ 6.20%")).toBeInTheDocument();

    // Per-cap movers, defaulting to the Large cap tier.
    expect(screen.getByText("Top 5 gainers")).toBeInTheDocument();
    expect(screen.getByText("Top 5 losers")).toBeInTheDocument();
    // Each mover now appears twice: once in the Top 3 strip and once in its cap-tier list.
    expect(screen.getAllByText("LGAIN")).toHaveLength(2);
    expect(screen.getAllByText("LLOSE")).toHaveLength(2);
    expect(screen.getByText("Top 3 gainers")).toBeInTheDocument();
    expect(screen.getByText("Top 3 losers")).toBeInTheDocument();
    expect(screen.getByText("Ranked within Large Cap · 60 stocks tracked")).toBeInTheDocument();

    // The three benchmarks, with their live level and today's move.
    expect(screen.getByText("Benchmark indices")).toBeInTheDocument();
    expect(screen.getByLabelText("NIFTY 50, 24,624.65, +0.04%")).toBeInTheDocument();
    expect(screen.getByLabelText("SENSEX, 78,581.00, +0.19%")).toBeInTheDocument();
    expect(screen.getByLabelText("Bank NIFTY, 57,739.95, -0.29%")).toBeInTheDocument();

    expect(screen.getByText("AI capex boom")).toBeInTheDocument();
    expect(screen.getByText("Rate-cut hopes")).toBeInTheDocument();
    expect(screen.getByText("Watch: Banking")).toBeInTheDocument();
    expect(screen.getByText("Watch: IT")).toBeInTheDocument();
  });

  it("renders the Neutral and Risk-Off moods, heuristic source, negative average move, and missing gainer/loser", async () => {
    mockFetch({
      ...baseState,
      mood: "Neutral",
      source: "heuristic",
      breadth: {
        ...baseState.breadth,
        advancing: 0,
        declining: 0,
        averageChangePercent: -0.4,
        topGainer: null,
        topLoser: null,
      },
      themes: ["Cautious sentiment"],
      sectorsToWatch: ["Pharma"],
    });
    render(<MarketPulse />);

    expect(await screen.findByText("Neutral")).toBeInTheDocument();
    expect(screen.getByText(/Heuristic \(no AI key configured\)/)).toBeInTheDocument();
    expect(screen.getByText("-0.40%")).toBeInTheDocument();
    // topGainer/topLoser null -> em dash fallback, plus the A/D ratio, which has no reading on a
    // tape where nothing advanced or declined.
    expect(screen.getAllByText("—")).toHaveLength(3);
  });

  /**
   * The board no longer waits on the model, so a composed summary has two meanings now. Telling a
   * reader the key is missing while a narrative is seconds away would simply be untrue.
   */
  it("says the agent is still writing rather than blaming a missing key", async () => {
    mockFetch({ ...baseState, source: "heuristic", narrativePending: true });
    render(<MarketPulse />);

    expect(await screen.findByText(/AI agent still writing/)).toBeInTheDocument();
    expect(screen.queryByText(/no AI key configured/)).not.toBeInTheDocument();
  });

  it("renders the Risk-Off mood", async () => {
    mockFetch({ ...baseState, mood: "Risk-Off" });
    render(<MarketPulse />);
    expect(await screen.findByText("Risk-Off")).toBeInTheDocument();
  });

  it("shows an error banner when the response is not ok", async () => {
    mockFetch({}, false);
    render(<MarketPulse />);
    expect(await screen.findByText(/Couldn't reach the market data feed/)).toBeInTheDocument();
  });

  it("shows an error banner when the fetch rejects", async () => {
    global.fetch = jest.fn().mockRejectedValue(new Error("network down"));
    render(<MarketPulse />);
    expect(await screen.findByText(/Couldn't reach the market data feed/)).toBeInTheDocument();
  });

  it("shows the generic unavailable message when the response succeeds but the body is null", async () => {
    mockFetch(null);
    render(<MarketPulse />);
    expect(await screen.findByText("Market pulse unavailable right now.")).toBeInTheDocument();
  });

  it("ranks the sharpest moves across every cap tier, not just the largest", async () => {
    mockFetch({
      ...baseState,
      breadth: {
        ...baseState.breadth,
        movers: {
          Large: {
            tracked: 60,
            gainers: [{ symbol: "BIGUP", name: "Big Up Ltd", sector: "Banking", capTier: "Large", price: 500, changePercent: 3.1 }],
            losers: [],
          },
          Mid: {
            tracked: 90,
            gainers: [{ symbol: "MIDUP", name: "Mid Up Ltd", sector: "Pharma", capTier: "Mid", price: 200, changePercent: 9.4 }],
            losers: [],
          },
          Small: {
            tracked: 50,
            gainers: [{ symbol: "SMLUP", name: "Small Up Ltd", sector: "Realty", capTier: "Small", price: 40, changePercent: 6.2 }],
            losers: [],
          },
        },
      },
    });
    render(<MarketPulse />);

    await screen.findByText("Top 3 gainers");
    const strip = screen.getByText("Top 3 gainers").parentElement!;
    // The mid cap moved most, so it leads the merged ranking.
    expect(within(strip).getAllByRole("listitem").map((row) => row.textContent)).toEqual([
      expect.stringContaining("MIDUP"),
      expect.stringContaining("SMLUP"),
      expect.stringContaining("BIGUP"),
    ]);
  });
});

// The live index poll keeps running on a 500ms interval while the exchange is open, so a
// response that lands after the panel has left must be dropped rather than pushed into an
// unmounted component.
describe("live index polling", () => {
  afterEach(() => {
    jest.useRealTimers();
  });

  it("ignores a poll that returns after the panel has been unmounted", async () => {
    jest.useFakeTimers();
    // 11:30 IST on the same trading day the fixture last printed a trade, so the session reads
    // as open and the poll actually starts.
    jest.setSystemTime(new Date("2026-08-04T06:00:00Z"));

    let resolveLive: ((value: unknown) => void) | null = null;
    global.fetch = jest.fn((url: string) => {
      if (url === "/api/market/live") {
        return new Promise((resolve) => {
          resolveLive = resolve;
        });
      }
      return Promise.resolve({ ok: true, json: async () => baseState } as Response);
    }) as unknown as typeof fetch;

    const { unmount } = render(<MarketPulse />);
    await act(async () => {
      jest.advanceTimersByTime(1000);
    });

    const resolve = resolveLive as unknown as (value: unknown) => void;
    expect(resolve).toEqual(expect.any(Function));

    const failed = jest.spyOn(console, "error").mockImplementation(() => {});
    unmount();
    resolve({ ok: true, json: async () => ({ indices: baseState.indices, asOf: "2026-08-04T06:00:00.000Z" }) });
    await act(async () => {
      await Promise.resolve();
      await Promise.resolve();
    });

    // A setState on an unmounted component is what this guards against.
    expect(failed).not.toHaveBeenCalled();
    failed.mockRestore();
  });
});

// Outside the session the automatic poll is off by design, so the button is the only way to ask
// for a fresh level — and it has to work whether the poll is running or not.
describe("manual index refresh", () => {
  it("pulls the levels again on request and shows the new one", async () => {
    const user = userEvent.setup();
    let level = 78581;
    global.fetch = jest.fn(async (url: string) => {
      if (url === "/api/market/live") {
        level += 100;
        return {
          ok: true,
          json: async () => ({
            indices: [{ ...baseState.indices[1], price: level }],
            asOf: "2026-08-05T10:00:00.000Z",
          }),
        } as unknown as Response;
      }
      return { ok: true, json: async () => baseState } as unknown as Response;
    }) as unknown as typeof fetch;

    render(<MarketPulse />);
    await screen.findByText("SENSEX");

    await user.click(screen.getByRole("button", { name: /Refresh/ }));

    // The button asks the live endpoint directly, whether or not the interval is running.
    await waitFor(() => expect(global.fetch).toHaveBeenCalledWith("/api/market/live"));
  });
});

describe("topMovers", () => {
  // The breadth payload can arrive before the movers are computed; ranking nothing must not throw.
  it("has nothing to rank without a movers payload", () => {
    expect(topMovers(undefined, "gainers", 3)).toEqual([]);
  });
});

describe("narrativeProvenance", () => {
  it("names all three states the summary can be in", () => {
    expect(narrativeProvenance("ai", false)).toBe("Generated by AI agent");
    expect(narrativeProvenance("heuristic", true)).toBe("Composed from the numbers · AI agent still writing");
    expect(narrativeProvenance("heuristic", false)).toBe("Heuristic (no AI key configured)");
  });

  // A summary the model wrote is the model's work whatever else is in flight.
  it("never calls a finished AI summary pending", () => {
    expect(narrativeProvenance("ai", true)).toBe("Generated by AI agent");
  });
});
