import { render, screen, fireEvent, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { TopPicksToday } from "../../app/components/top-picks-today";

// Only the data layer behind the price/returns strip is stubbed — the real LiveMarketValue and
// StockReturns still render, so these tests keep asserting that each card is actually wired to
// the live feed. BBB stands in for a symbol the feed has no data for.
jest.mock("../../app/components/use-stock-performance", () => ({
  useStockPerformance: (symbol: string | null) => ({
    performance:
      symbol && symbol !== "BBB"
        ? {
            symbol,
            currency: "INR",
            price: 111.11,
            oneDay: 3.33,
            oneWeek: 1.11,
            oneMonth: -2.22,
            sixMonth: 12.5,
            oneYear: 40,
            threeYear: 150.5,
            fiveYear: 480,
            overall: 12345,
            overallSince: "1999-04-01",
          }
        : null,
    loading: false,
  }),
}));

jest.mock("../../app/components/ai-report-modal-lazy", () => ({
  AiReportModal: (props: any) => (
    <div
      data-testid="ai-report-modal"
      data-open={String(props.open)}
      data-symbol={props.analysis?.stock ?? ""}
      data-logo={props.logoUrl ?? ""}
      data-company={props.companyName ?? ""}
      data-loading={String(props.loading)}
    >
      <button data-testid="modal-close" onClick={props.onClose}>
        close
      </button>
    </div>
  ),
}));

function mockFetchOnce(response: unknown, ok = true) {
  global.fetch = jest.fn().mockResolvedValue({
    ok,
    json: async () => response,
  } as Response);
}

const basePicks = [
  {
    symbol: "AAA",
    name: "Alpha Co",
    sector: "Information Technology",
    logo: "https://logo.test/a.png",
    price: 100.5,
    changePercent: 2.5,
    outlook: "Bullish",
    confidence: 80,
    analysis: {
      stock: "AAA",
      recommendation: "Strong Outperform",
      recommendationReasons: ["reason1"],
      keyInsights: ["insight-a"],
    },
  },
  {
    symbol: "BBB",
    name: "Beta Co",
    sector: "Automobile",
    logo: "https://logo.test/b.png",
    price: null,
    changePercent: null,
    outlook: "Bearish",
    confidence: 60,
    analysis: {
      stock: "BBB",
      recommendation: "Avoid for now",
      recommendationReasons: [],
      keyInsights: ["insight-b"],
    },
  },
  {
    symbol: "CCC",
    name: "Gamma Co",
    sector: "Pharmaceuticals",
    logo: "https://logo.test/c.png",
    price: 50,
    changePercent: -1.2,
    outlook: "Neutral",
    confidence: 50,
    analysis: {
      stock: "CCC",
      recommendation: "Hold steady",
      recommendationReasons: [],
      keyInsights: [],
    },
  },
  {
    symbol: "DDD",
    name: "Delta Co",
    sector: "Banking",
    logo: "https://logo.test/d.png",
    price: 20,
    changePercent: 0,
    outlook: "Neutral",
    confidence: 40,
    analysis: {
      stock: "DDD",
      recommendationReasons: [],
      keyInsights: [],
    },
  },
];

describe("TopPicksToday", () => {
  it("shows loading skeletons before data arrives", () => {
    global.fetch = jest.fn(() => new Promise(() => {})) as unknown as typeof fetch;
    const { container } = render(<TopPicksToday />);
    expect(screen.getByText("Loading…")).toBeInTheDocument();
    expect(container.querySelectorAll(".animate-pulse")).toHaveLength(6);
  });

  it("renders picks covering outlook, recommendation, why, price and change branches", async () => {
    const fixedNow = new Date("2026-08-04T12:00:00.000Z").getTime();
    jest.spyOn(Date, "now").mockReturnValue(fixedNow);
    const generatedAt = new Date(fixedNow - 30 * 60000).toISOString();

    mockFetchOnce({ date: "2026-08-04", generatedAt, source: "ai", picks: basePicks });
    render(<TopPicksToday />);

    expect(await screen.findByText("AAA")).toBeInTheDocument();
    expect(screen.getByText("Generated by AI agent")).toBeInTheDocument();
    expect(screen.getByText("Updated 30m ago")).toBeInTheDocument();

    // Top pick badge only on first card
    expect(screen.getAllByText("★ Top pick")).toHaveLength(1);

    // The live quote wins over the price snapshot baked into the daily picks cache (₹100.50).
    const aaaCard = screen.getByText("AAA").closest("button")!;
    expect(within(aaaCard).getByText("₹111.11")).toBeInTheDocument();
    // Today's move appears twice: once next to the price, once as the 1D cell of the strip.
    expect(within(aaaCard).getAllByText("+3.33%")).toHaveLength(2);

    // Every card carries the full trailing-return strip.
    expect(within(aaaCard).getByText("+1.11%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("-2.22%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("+12.50%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("+40.00%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("+150.5%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("+480.0%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("+12345%")).toBeInTheDocument();
    expect(within(aaaCard).getByText("Returns")).toBeInTheDocument();
    expect(within(aaaCard).getByText("since 1999")).toBeInTheDocument();

    // With no feed data, price, today's move and all eight return cells fall back to a dash.
    const bbbCard = screen.getByText("BBB").closest("button")!;
    expect(within(bbbCard).getAllByText("—")).toHaveLength(10);

    const cccCard = screen.getByText("CCC").closest("button")!;
    expect(within(cccCard).getByText("₹111.11")).toBeInTheDocument();

    // Outlook badges (all three variants)
    expect(screen.getByText("Bullish · 80%")).toBeInTheDocument();
    expect(screen.getByText("Bearish · 60%")).toBeInTheDocument();
    expect(screen.getAllByText("Neutral · 50%").length).toBeGreaterThan(0);

    // Recommendation badges (AAA and DDD both default to Outperform; DDD has no recommendation field)
    expect(within(aaaCard).getByText("Outperform")).toBeInTheDocument();
    const dddCard = screen.getByText("DDD").closest("button")!;
    expect(within(dddCard).getByText("Outperform")).toBeInTheDocument();
    expect(within(bbbCard).getByText("Avoid")).toBeInTheDocument();
    expect(within(cccCard).getByText("Hold")).toBeInTheDocument();

    // Why text: recommendationReasons wins, then keyInsights, then absent
    expect(within(aaaCard).getByText("reason1")).toBeInTheDocument();
    expect(within(bbbCard).getByText("insight-b")).toBeInTheDocument();
    expect(within(cccCard).queryByText(/Why:/)).not.toBeInTheDocument();
  });

  it("shows heuristic source label and hides Updated line when generatedAt is empty", async () => {
    mockFetchOnce({ date: "2026-08-04", generatedAt: "", source: "heuristic", picks: [] });
    render(<TopPicksToday />);
    expect(await screen.findByText("Heuristic demo (no AI key configured)")).toBeInTheDocument();
    expect(screen.queryByText(/^Updated/)).not.toBeInTheDocument();
  });

  it.each([
    [0, "just now"],
    [300, "5h ago"],
    [3000, "2d ago"],
  ])("formats relative time for %sm ago as %s", async (minutesAgo, expected) => {
    const fixedNow = new Date("2026-08-04T12:00:00.000Z").getTime();
    jest.spyOn(Date, "now").mockReturnValue(fixedNow);
    const generatedAt = new Date(fixedNow - minutesAgo * 60000).toISOString();
    mockFetchOnce({ date: "2026-08-04", generatedAt, source: "ai", picks: [] });
    render(<TopPicksToday />);
    expect(await screen.findByText(`Updated ${expected}`)).toBeInTheDocument();
  });

  it("shows an error banner when the response is not ok", async () => {
    mockFetchOnce({}, false);
    render(<TopPicksToday />);
    expect(await screen.findByText(/Couldn't reach the AI picks engine/)).toBeInTheDocument();
  });

  it("shows an error banner when the fetch rejects", async () => {
    global.fetch = jest.fn().mockRejectedValue(new Error("network down"));
    render(<TopPicksToday />);
    expect(await screen.findByText(/Couldn't reach the AI picks engine/)).toBeInTheDocument();
  });

  it("shows the empty state when there are no picks and no error", async () => {
    mockFetchOnce({ date: "2026-08-04", generatedAt: "", source: "ai", picks: [] });
    render(<TopPicksToday />);
    expect(await screen.findByText(/No picks available right now/)).toBeInTheDocument();
  });

  it("falls back to initials when the logo image fails to load", async () => {
    mockFetchOnce({ date: "2026-08-04", generatedAt: "", source: "ai", picks: [basePicks[0]] });
    render(<TopPicksToday />);
    const img = await screen.findByAltText("Alpha Co logo");
    fireEvent.error(img);
    expect(screen.getByText("A")).toBeInTheDocument();
  });

  it("selects a pick, opens the modal with its analysis, and closes it", async () => {
    const user = userEvent.setup();
    mockFetchOnce({ date: "2026-08-04", generatedAt: "", source: "ai", picks: basePicks });
    render(<TopPicksToday />);

    await screen.findByText("AAA");
    expect(screen.getByTestId("ai-report-modal")).toHaveAttribute("data-open", "false");

    const aaaCard = screen.getByText("AAA").closest("button")!;
    await user.click(aaaCard);

    const modal = screen.getByTestId("ai-report-modal");
    expect(modal).toHaveAttribute("data-open", "true");
    expect(modal).toHaveAttribute("data-symbol", "AAA");
    expect(modal).toHaveAttribute("data-logo", "https://logo.test/a.png");
    expect(modal).toHaveAttribute("data-company", "Alpha Co");
    expect(within(aaaCard).getByText("Viewing full report ↗")).toBeInTheDocument();

    await user.click(screen.getByTestId("modal-close"));
    expect(screen.getByTestId("ai-report-modal")).toHaveAttribute("data-open", "false");
  });
});
